### ISSUE TITLE
v0.8.2 has a breaking change 

### ISSUE THREAD

**Issue by pedrobernardina** [vtex-apps/store-link#55]
This week we realized that none of our modal were working. After some debugging, we discovered that StoreLink was not working as a trigger anymore. I believe it's common to use StoreLink as a button in store-theme, and in our store it is used mostly as a modal trigger.

Investiganting this repo, I suspected that the problem was with v0.8.2. Manually installing v0.8.1 confirmed my suspicions, as everything started working again.

Checking the tags history, commit 9c5cbf60abf886b999711f4f18fd1f574669fb5b introduced the following change:

```js
 const handlePrevent = (e: React.MouseEvent) =>{
    e.stopPropagation()
    e.nativeEvent.stopImmediatePropagation()
}

<div onClick={handlePrevent} className={handles.linkContainer}>
  <Link
        to={resolvedLink}
        target={target}
        className={rootClasses}
        scrollOptions={scrollOptions}
        rel={rel}
        onClick={handlePrevent}
      >
        {label && <span className={labelClasses}>{localizedLabel}</span>}
        {hasChildren(children) && (
          <div className={handles.childrenContainer}>{children}</div>
        )}
      </Link>
    </div>
```

In fact, this is a breaking change, as previous expected behaviour is not working as intended anymore.

I suggest:
  1. Adding a control prop to stop propagation or not; or
  2. Releasing a major version instead.
  
Tagging @jpesce for visibility.

**Comment by filipewl** [comment]
Thanks for the report @pedrobernardina!

We deployed version [v0.9.2](https://github.com/vtex-apps/store-link/pull/57) with a rollback of the changes from [v0.8.2](https://github.com/vtex-apps/store-link/pull/52).

Please let us know if you encountered any issues by re-opening this issue.
